

front_left_wheel_pid:
  p: 1.0
  i: 0.1
  d: 0.05
  i_clamp: 1.0
front_right_wheel_pid:
  p: 1.0
  i: 0.1
  d: 0.05
  i_clamp: 1.0

back_left_wheel_pid:
  p: 1.0
  i: 0.1
  d: 0.05
  i_clamp: 1.0

back_right_wheel_pid:
  p: 1.0
  i: 0.1
  d: 0.05
  i_clamp: 1.0



controller:
  hero_chassis_controller:
    type: hero_chassis_controller/CqcLastWorkController

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


