controller:
    hero_chassis_controller:
       type: hero_chassis_controller/CqcLastWorkController
       

    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
