controller:

    CqcLastworkController:
       type: hero_chassis_controller/CqcLastworkController

    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
